services:
  golang:
    build: . # pakai Dockerfile di current dir
    container_name: golang_container
    depends_on:
      - postgres # tunggu postgres jalan dulu
    ports:
      - "8080:8080" # map ke host
    networks:
      - portofolio_network
    # command: ["./wait-for-postgres.sh", "postgres"]

  postgres:
    image: postgres:13.22-alpine3.22
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pos
    volumes:
      - postgres_alpine_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - portofolio_network

networks:
  portofolio_network:
    driver: bridge
    external: true
volumes:
  postgres_alpine_data:
    name: postgres_alpine_data
    external: true
